import { describe, test, expect, beforeEach, afterEach, mock } from "bun:test"
import { Tool } from "../tool"
import z from "zod"

describe("Tool", () => {
  describe("define", () => {
    test("should create tool with static implementation", () => {
      const tool = Tool.define("test", {
        description: "Test tool",
        parameters: z.object({ input: z.string() }),
        execute: async (params, ctx) => ({
          title: "Test",
          output: params.input,
          metadata: {},
        }),
      })

      expect(tool.id).toBe("test")
    })

    test("should create tool with function implementation", () => {
      const tool = Tool.define("test", async () => ({
        description: "Test tool",
        parameters: z.object({ input: z.string() }),
        execute: async (params, ctx) => ({
          title: "Test",
          output: params.input,
          metadata: {},
        }),
      }))

      expect(tool.id).toBe("test")
    })

    test("should initialize static implementation", async () => {
      const tool = Tool.define("test", {
        description: "Test tool",
        parameters: z.object({ input: z.string() }),
        execute: async (params, ctx) => ({
          title: "Test",
          output: params.input,
          metadata: {},
        }),
      })

      const init = await tool.init()
      expect(init.description).toBe("Test tool")
      expect(init.parameters).toBeDefined()
      expect(init.execute).toBeDefined()
    })

    test("should initialize function implementation", async () => {
      const tool = Tool.define("test", async () => ({
        description: "Dynamic test tool",
        parameters: z.object({ input: z.string() }),
        execute: async (params, ctx) => ({
          title: "Test",
          output: params.input,
          metadata: {},
        }),
      }))

      const init = await tool.init()
      expect(init.description).toBe("Dynamic test tool")
    })

    test("should validate parameters on execute", async () => {
      const tool = Tool.define("test", {
        description: "Test tool",
        parameters: z.object({ input: z.string().min(1) }),
        execute: async (params, ctx) => ({
          title: "Test",
          output: params.input,
          metadata: {},
        }),
      })

      const init = await tool.init()
      const mockCtx = {
        sessionID: "test",
        messageID: "test",
        agent: "test",
        abort: new AbortController().signal,
        messages: [],
        metadata: mock(() => {}),
        ask: mock(async () => {}),
      }

      // Valid params
      const result = await init.execute({ input: "hello" }, mockCtx)
      expect(result.output).toBe("hello")

      // Invalid params - should throw
      await expect(init.execute({ input: "" }, mockCtx)).rejects.toThrow()
    })

    test("should use custom formatValidationError", async () => {
      const tool = Tool.define("test", {
        description: "Test tool",
        parameters: z.object({ input: z.string().min(1) }),
        formatValidationError: (error) => `Custom error: ${error.issues[0].message}`,
        execute: async (params, ctx) => ({
          title: "Test",
          output: params.input,
          metadata: {},
        }),
      })

      const init = await tool.init()
      const mockCtx = {
        sessionID: "test",
        messageID: "test",
        agent: "test",
        abort: new AbortController().signal,
        messages: [],
        metadata: mock(() => {}),
        ask: mock(async () => {}),
      }

      await expect(init.execute({ input: "" }, mockCtx)).rejects.toThrow("Custom error")
    })

    test("should pass init context to function implementation", async () => {
      const tool = Tool.define("test", async (ctx) => ({
        description: ctx?.agent ? `Tool for ${ctx.agent}` : "Generic tool",
        parameters: z.object({}),
        execute: async () => ({
          title: "Test",
          output: "ok",
          metadata: {},
        }),
      }))

      const initWithCtx = await tool.init({ agent: { name: "test-agent" } as any })
      // The description is generated by the function, which may format the agent object differently
      expect(initWithCtx.description).toBeDefined()
      expect(initWithCtx.description.length).toBeGreaterThan(0)

      const initWithoutCtx = await tool.init()
      expect(initWithoutCtx.description).toBe("Generic tool")
    })
  })

  describe("Context", () => {
    test("should have required context properties", () => {
      const mockCtx: Tool.Context = {
        sessionID: "test-session",
        messageID: "test-message",
        agent: "test-agent",
        abort: new AbortController().signal,
        messages: [],
        metadata: () => {},
        ask: async () => {},
      }

      expect(mockCtx.sessionID).toBe("test-session")
      expect(mockCtx.messageID).toBe("test-message")
      expect(mockCtx.agent).toBe("test-agent")
      expect(mockCtx.abort).toBeDefined()
      expect(mockCtx.messages).toBeDefined()
      expect(mockCtx.metadata).toBeDefined()
      expect(mockCtx.ask).toBeDefined()
    })
  })

  describe("Info", () => {
    test("should have required info properties", () => {
      const tool: Tool.Info = {
        id: "test",
        init: async () => ({
          description: "Test",
          parameters: z.object({}),
          execute: async () => ({
            title: "Test",
            output: "ok",
            metadata: {},
          }),
        }),
      }

      expect(tool.id).toBe("test")
      expect(tool.init).toBeDefined()
    })
  })
})